// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sbrhevrjvnkjkjgnflrd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNicmhldnJqdm5ramtqZ25mbHJkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg4OTMzODcsImV4cCI6MjA2NDQ2OTM4N30.Yami7RdSgdFB9qx61n9SLGr3-eTAcn7kdnaOUkdFDsM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);